import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  guideSidebar: [
    {
      type: "doc",
      id: "getting-started",
      label: "Getting Started",
    },
    {
      type: "category",
      label: "Usage",
      items: [
        "usage/extraction",
        "usage/compression",
        "usage/password",
        "usage/cancellation",
      ],
    },
    {
      type: "doc",
      id: "performance",
      label: "Performance",
    },
  ],
  apiSidebar: [
    {
      type: "autogenerated",
      dirName: "api",
    },
  ],
};

export default sidebars;
